### ISSUE TITLE
Not able to reproduce the same result from the EML4-ALK cell line sample

### ISSUE THREAD

**Issue by land-mine** [sgilab/JuLI#1]
I have been trying to reproduce the same result of your published paper sample: 
https://www.ebi.ac.uk/ena/data/view/SRR8427184
I ran the fastq file in bwa-mem and samtools then loaded with your callfusion() and annotation without changing any default parameters but getting single gene fusing with itself. i checked with the log file and the targeted fusion log says "Unmatched contig sequences" in both D log and P log. Can you direct me to get the result??
i have  attached the log file here:
[H2228.log](https://github.com/sgilab/JuLI/files/3878893/H2228.log)

>callfusion(CaseBam='~/Downloads/H2228.bam',TestID='H2228', OutputPath='Output/', Thread=3, Refgene='references/refGene_hg19.txt', Gap='references/gap_hg19.txt', Reference='~/GeneFuse/hg19.fa', Log=TRUE)
[H2228.annotated.gene.pdf]

>callfusion(CaseBam=~/Downloads/H2228.bam,ControlBam=NULL,TestID=H2228,OutputPath=Output/,Thread=3,ControlPanel=NULL,TargetBed=NULL,Refgene=references/refGene_hg19.txt,Gap=references/gap_hg19.txt,Reference=~/GeneFuse/hg19.fa,AnalysisType=DP,AnalysisUnit=1000,MinMappingQuality=0,SplitCutoff=2,DiscordantCutoff=3,NucDiv=TRUE,SplitRatio=0.7,MatchBase=10,Log=TRUE)
[2019-Nov-22 09:43:10] JuLI v0.1.3
[2019-Nov-22 09:43:10] Measuring bam statistics
[2019-Nov-22 09:43:20] Identifying candidate breaks
[2019-Nov-22 09:44:00] Analysing discordant pairs
[2019-Nov-22 09:44:00] -Counting supporting reads
[2019-Nov-22 09:47:22] -Generating consensus contigs
[2019-Nov-22 09:47:24] -Comparing contigs betweem breaks
[2019-Nov-22 09:47:25] Analysing proper pairs
[2019-Nov-22 09:47:25] -Counting supporting reads
[2019-Nov-22 09:47:40] -Generating consensus contigs
[2019-Nov-22 09:48:02] -Comparing contigs betweem breaks
Column 1 ['X1'] of item 3 is missing in item 1. Use fill=TRUE to fill with NA (NULL for list columns), or use.names=FALSE to ignore column names. use.names='check' (default from v1.12.2) emits this message and proceeds as if use.names=FALSE for  backwards compatibility. See news item 5 in v1.12.2 for options to control this message.
[2019-Nov-22 09:48:10] Output generation
[2019-Nov-22 09:48:10] Done
> annofusion(Output='Output/H2228.txt', Refgene='references/refGene_hg19.txt', Cosmic='references/CosmicFusionExport.tsv', Pfam='references/Pfam-A.full.human', Uniprot='references/HGNC_GeneName_UniProtID_160524.txt')
[2019-Nov-22 09:51:47] Annotation and visualization start
[2019-Nov-22 09:51:50] Annotation and visualization finish
PDF: (https://github.com/sgilab/JuLI/files/3878914/H2228.annotated.gene.pdf)

**Comment by sgilab** [comment]
Sorry for the delayed response.

I think the BAM had a problem with paired-end alignment. Please check the BAM processing. I attached my output of the cell-line BAM.

HT

[CS11_14_01876.sorted.unfiltered.txt](https://github.com/sgilab/JuLI/files/4513955/CS11_14_01876.sorted.unfiltered.txt)
